const countries: Map<string, string> = new Map<string, string>();
countries.set('Andorra', 'AD');
countries.set('United Arab Emirates', 'AE');
countries.set('Afghanistan', 'AF');
countries.set('Antigua and Barbuda', 'AG');
countries.set('Anguilla', 'AI');
countries.set('Albania', 'AL');
countries.set('Armenia', 'AM');
countries.set('Angola', 'AO');
countries.set('Antarctica', 'AQ');
countries.set('Argentina', 'AR');
countries.set('American Samoa', 'AS');
countries.set('Austria', 'AT');
countries.set('Australia', 'AU');
countries.set('Aruba', 'AW');
countries.set('Åland Islands', 'AX');
countries.set('Azerbaijan', 'AZ');
countries.set('Bosnia and Herzegovina', 'BA');
countries.set('Barbados', 'BB');
countries.set('Bangladesh', 'BD');
countries.set('Belgium', 'BE');
countries.set('Burkina Faso', 'BF');
countries.set('Bulgaria', 'BG');
countries.set('Bahrain', 'BH');
countries.set('Burundi', 'BI');
countries.set('Benin', 'BJ');
countries.set('Saint Barthélemy', 'BL');
countries.set('Bermuda', 'BM');
countries.set('Brunei Darussalam', 'BN');
countries.set('Bolivia (Plurinational State of)', 'BO');
countries.set('Bonaire, Sint Eustatius and Saba', 'BQ');
countries.set('Brazil', 'BR');
countries.set('Bahamas', 'BS');
countries.set('Bhutan', 'BT');
countries.set('Bouvet Island', 'BV');
countries.set('Botswana', 'BW');
countries.set('Belarus', 'BY');
countries.set('Belize', 'BZ');
countries.set('Canada', 'CA');
countries.set('Cocos (Keeling) Islands', 'CC');
countries.set('Congo, Democratic Republic of the', 'CD');
countries.set('Central African Republic', 'CF');
countries.set('Congo', 'CG');
countries.set('Switzerland', 'CH');
countries.set('Côte d\'Ivoire', 'CI');
countries.set('Cook Islands', 'CK');
countries.set('Chile', 'CL');
countries.set('Cameroon', 'CM');
countries.set('China', 'CN');
countries.set('Colombia', 'CO');
countries.set('Costa Rica', 'CR');
countries.set('Cuba', 'CU');
countries.set('Cabo Verde', 'CV');
countries.set('Curaçao', 'CW');
countries.set('Christmas Island', 'CX');
countries.set('Cyprus', 'CY');
countries.set('Czechia', 'CZ');
countries.set('Germany', 'DE');
countries.set('Djibouti', 'DJ');
countries.set('Denmark', 'DK');
countries.set('Dominica', 'DM');
countries.set('Dominican Republic', 'DO');
countries.set('Algeria', 'DZ');
countries.set('Ecuador', 'EC');
countries.set('Estonia', 'EE');
countries.set('Egypt', 'EG');
countries.set('Western Sahara', 'EH');
countries.set('Eritrea', 'ER');
countries.set('Spain', 'ES');
countries.set('Ethiopia', 'ET');
countries.set('Finland', 'FI');
countries.set('Fiji', 'FJ');
countries.set('Falkland Islands (Malvinas)', 'FK');
countries.set('Micronesia (Federated States of)', 'FM');
countries.set('Faroe Islands', 'FO');
countries.set('France', 'FR');
countries.set('Gabon', 'GA');
countries.set('United Kingdom of Great Britain and Northern Ireland', 'GB');
countries.set('Grenada', 'GD');
countries.set('Georgia', 'GE');
countries.set('French Guiana', 'GF');
countries.set('Guernsey', 'GG');
countries.set('Ghana', 'GH');
countries.set('Gibraltar', 'GI');
countries.set('Greenland', 'GL');
countries.set('Gambia', 'GM');
countries.set('Guinea', 'GN');
countries.set('Guadeloupe', 'GP');
countries.set('Equatorial Guinea', 'GQ');
countries.set('Greece', 'GR');
countries.set('South Georgia and the South Sandwich Islands', 'GS');
countries.set('Guatemala', 'GT');
countries.set('Guam', 'GU');
countries.set('Guinea-Bissau', 'GW');
countries.set('Guyana', 'GY');
countries.set('Hong Kong', 'HK');
countries.set('Heard Island and McDonald Islands', 'HM');
countries.set('Honduras', 'HN');
countries.set('Croatia', 'HR');
countries.set('Haiti', 'HT');
countries.set('Hungary', 'HU');
countries.set('Indonesia', 'ID');
countries.set('Ireland', 'IE');
countries.set('Israel', 'IL');
countries.set('Isle of Man', 'IM');
countries.set('India', 'IN');
countries.set('British Indian Ocean Territory', 'IO');
countries.set('Iraq', 'IQ');
countries.set('Iran (Islamic Republic of)', 'IR');
countries.set('Iceland', 'IS');
countries.set('Italy', 'IT');
countries.set('Jersey', 'JE');
countries.set('Jamaica', 'JM');
countries.set('Jordan', 'JO');
countries.set('Japan', 'JP');
countries.set('Kenya', 'KE');
countries.set('Kyrgyzstan', 'KG');
countries.set('Cambodia', 'KH');
countries.set('Kiribati', 'KI');
countries.set('Comoros', 'KM');
countries.set('Saint Kitts and Nevis', 'KN');
countries.set('Korea (Democratic People\'s Republic of)', 'KP');
countries.set('Korea, Republic of', 'KR');
countries.set('Kuwait', 'KW');
countries.set('Cayman Islands', 'KY');
countries.set('Kazakhstan', 'KZ');
countries.set('Lao People\'s Democratic Republic', 'LA');
countries.set('Lebanon', 'LB');
countries.set('Saint Lucia', 'LC');
countries.set('Liechtenstein', 'LI');
countries.set('Sri Lanka', 'LK');
countries.set('Liberia', 'LR');
countries.set('Lesotho', 'LS');
countries.set('Lithuania', 'LT');
countries.set('Luxembourg', 'LU');
countries.set('Latvia', 'LV');
countries.set('Libya', 'LY');
countries.set('Morocco', 'MA');
countries.set('Monaco', 'MC');
countries.set('Moldova, Republic of', 'MD');
countries.set('Montenegro', 'ME');
countries.set('Saint Martin (French part)', 'MF');
countries.set('Madagascar', 'MG');
countries.set('Marshall Islands', 'MH');
countries.set('North Macedonia', 'MK');
countries.set('Mali', 'ML');
countries.set('Myanmar', 'MM');
countries.set('Mongolia', 'MN');
countries.set('Macao', 'MO');
countries.set('Northern Mariana Islands', 'MP');
countries.set('Martinique', 'MQ');
countries.set('Mauritania', 'MR');
countries.set('Montserrat', 'MS');
countries.set('Malta', 'MT');
countries.set('Mauritius', 'MU');
countries.set('Maldives', 'MV');
countries.set('Malawi', 'MW');
countries.set('Mexico', 'MX');
countries.set('Malaysia', 'MY');
countries.set('Mozambique', 'MZ');
countries.set('Namibia', 'NA');
countries.set('New Caledonia', 'NC');
countries.set('Niger', 'NE');
countries.set('Norfolk Island', 'NF');
countries.set('Nigeria', 'NG');
countries.set('Nicaragua', 'NI');
countries.set('The Netherlands', 'NL');
countries.set('Norway', 'NO');
countries.set('Nepal', 'NP');
countries.set('Nauru', 'NR');
countries.set('Niue', 'NU');
countries.set('New Zealand', 'NZ');
countries.set('Oman', 'OM');
countries.set('Panama', 'PA');
countries.set('Peru', 'PE');
countries.set('French Polynesia', 'PF');
countries.set('Papua New Guinea', 'PG');
countries.set('Philippines', 'PH');
countries.set('Pakistan', 'PK');
countries.set('Poland', 'PL');
countries.set('Saint Pierre and Miquelon', 'PM');
countries.set('Pitcairn', 'PN');
countries.set('Puerto Rico', 'PR');
countries.set('Palestine, State of', 'PS');
countries.set('Portugal', 'PT');
countries.set('Palau', 'PW');
countries.set('Paraguay', 'PY');
countries.set('Qatar', 'QA');
countries.set('Réunion', 'RE');
countries.set('Romania', 'RO');
countries.set('Serbia', 'RS');
countries.set('Russian Federation', 'RU');
countries.set('Rwanda', 'RW');
countries.set('Saudi Arabia', 'SA');
countries.set('Solomon Islands', 'SB');
countries.set('Seychelles', 'SC');
countries.set('Sudan', 'SD');
countries.set('Sweden', 'SE');
countries.set('Singapore', 'SG');
countries.set('Saint Helena, Ascension and Tristan da Cunha', 'SH');
countries.set('Slovenia', 'SI');
countries.set('Svalbard and Jan Mayen', 'SJ');
countries.set('Slovakia', 'SK');
countries.set('Sierra Leone', 'SL');
countries.set('San Marino', 'SM');
countries.set('Senegal', 'SN');
countries.set('Somalia', 'SO');
countries.set('Suriname', 'SR');
countries.set('South Sudan', 'SS');
countries.set('Sao Tome and Principe', 'ST');
countries.set('El Salvador', 'SV');
countries.set('Sint Maarten (Dutch part)', 'SX');
countries.set('Syrian Arab Republic', 'SY');
countries.set('Eswatini', 'SZ');
countries.set('Turks and Caicos Islands', 'TC');
countries.set('Chad', 'TD');
countries.set('French Southern Territories', 'TF');
countries.set('Togo', 'TG');
countries.set('Thailand', 'TH');
countries.set('Tajikistan', 'TJ');
countries.set('Tokelau', 'TK');
countries.set('Timor-Leste', 'TL');
countries.set('Turkmenistan', 'TM');
countries.set('Tunisia', 'TN');
countries.set('Tonga', 'TO');
countries.set('Türkiye', 'TR');
countries.set('Trinidad and Tobago', 'TT');
countries.set('Tuvalu', 'TV');
countries.set('Taiwan, Province of China', 'TW');
countries.set('Tanzania, United Republic of', 'TZ');
countries.set('Ukraine', 'UA');
countries.set('Uganda', 'UG');
countries.set('United States Minor Outlying Islands', 'UM');
countries.set('United States', 'US');
countries.set('Uruguay', 'UY');
countries.set('Uzbekistan', 'UZ');
countries.set('Holy See', 'VA');
countries.set('Saint Vincent and the Grenadines', 'VC');
countries.set('Venezuela (Bolivarian Republic of)', 'VE');
countries.set('Virgin Islands (British)', 'VG');
countries.set('Virgin Islands (U.S.)', 'VI');
countries.set('Viet Nam', 'VN');
countries.set('Vanuatu', 'VU');
countries.set('Wallis and Futuna', 'WF');
countries.set('Samoa', 'WS');
countries.set('Yemen', 'YE');
countries.set('Mayotte', 'YT');
countries.set('South Africa', 'ZA');
countries.set('Zambia', 'ZM');
countries.set('Zimbabwe', 'ZW');

export default countries;
